spring:
  datasource:
<<<<<<< HEAD
    # 配置数据源信息 datasource:
    dynamic:
      # 设置默认的数据源或者数据源组,默认值即为master
      primary: master
      # 严格匹配数据源,默认false.true未匹配到指定数据源时抛异常,false使用默认数据源
      strict: false
      datasource:
        master:
          url: jdbc:mysql://localhost:3306/mybatis_plus?useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: 'hxl158120'
        slave_1:
          # 我的数据库是8.0.27 5版本的可以使用jdbc:mysql://localhost:3306/mybatis_plus?characterEncoding=utf-8&useSSL=false
          url: jdbc:mysql://localhost:3306/mybatis_plus_1?useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: 'hxl158120'

=======
    url: jdbc:mysql://localhost:3306/mybatis_plus?useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: hxl158120
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  mapper-locations: /mapper/**
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# 设置mybatis-plus全局配置
#  global-config:
#    db-config:
      # 设置数据库表名
#      table-prefix: t_
      # 设置主键生成策略
#      id-type: auto
  # 配置类型别名所对应的包
  type-aliases-package: com.ssm.mybatis_plus.pojo
#      logic-delete-field: flag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
#      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
#      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  # 扫描枚举的包
  type-enums-package: com.ssm.mybatis_plus.enums
>>>>>>> 07c231ce932f21b3503bcf7886386f72c3c45658
